import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { cleanDatabase } from '../src/utils/database.util';

describe('Ruta Crítica CRM: Eventos y Embudo (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let accessToken: string;

  // Variables para seguir el rastro del flujo
  let campaignId: string;
  let leadId: string;
  let dealId: string;
  let clientId: string;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true }));
    await app.init();

    prisma = app.get(PrismaService);
    await cleanDatabase(prisma);

    // Setup de autenticación
    const testEmail = `admin-${Date.now()}@econexium.com`;
    await request(app.getHttpServer())
      .post('/users')
      .send({ name: 'Admin Flow', email: testEmail, password: 'Password123!', role: 'admin' });

    const loginRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({ email: testEmail, password: 'Password123!' });

    accessToken = loginRes.body.accessToken;
  });

  afterAll(async () => {
    await cleanDatabase(prisma);
    await app.close();
  });

  it('1. POST /campaigns restringe la creación a canales permitidos', async () => {
    await request(app.getHttpServer())
      .post('/campaigns')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({ name: 'Campaña Fallida', channel: 'x' })
      .expect(400);

    const response = await request(app.getHttpServer())
      .post('/campaigns')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        name: 'Promo Cargadores EV',
        channel: 'tiktok',
      })
      .expect(201);

    campaignId = response.body.id;
  });

  it('2. POST /leads enlaza correctamente con la campaña', async () => {
    const response = await request(app.getHttpServer())
      .post('/leads')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        campaignId,
        name: 'Carlos FB',
        email: 'carlos@test.com',
        phone: '3001234567',
      })
      .expect(201);

    leadId = response.body.id;
  });

  it('3. POST /deals crea el trato sin permitir duplicados', async () => {
    const res = await request(app.getHttpServer())
      .post('/deals')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        leadId,
        installationType: 'CARGADOR',
        estimatedValue: 2500000,
      });

    if (res.status !== 201) {
      console.log('🚨 ERROR DE VALIDACIÓN EN DEALS:', res.body);
    }

    expect(res.status).toBe(201);
    dealId = res.body.id;

    await request(app.getHttpServer())
      .post('/deals')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        leadId,
        installationType: 'CARGADOR',
        estimatedValue: 2500000,
      })
      .expect(409);
  });

  it('4. PATCH /deals/:id a GANADO emite evento y crea el Cliente automáticamente', async () => {
    await request(app.getHttpServer())
      .patch(`/deals/${dealId}`)
      .set('Authorization', `Bearer ${accessToken}`)
      .send({ stage: 'GANADO' })
      .expect(200);

    // Los eventos son asíncronos, le damos tiempo a Nest para que
    // termine de ejecutar 'handleDealWon' en ClientsService antes de consultar.
    await new Promise((resolve) => setTimeout(resolve, 100));

    const clientsResponse = await request(app.getHttpServer())
      .get('/clients')
      .set('Authorization', `Bearer ${accessToken}`)
      .expect(200);

    const autoGeneratedClient = clientsResponse.body.find((c) => c.dealId === dealId);

    expect(autoGeneratedClient).toBeDefined();
    expect(autoGeneratedClient.name).toBe('Carlos FB');
    expect(autoGeneratedClient.email).toBe('carlos@test.com');

    clientId = autoGeneratedClient.id;
  });

  it('5. POST /inspections crea la inspección para el cliente real', async () => {
    const response = await request(app.getHttpServer())
      .post('/inspections')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        clientId,
        inspectorName: 'Samuel Pérez',
        systemType: 'TRIFASICO',
        originPoint: 'Tablero principal',
        hasPanelSpace: true,
        requiresDrilling: false,
        differentialProtectionRequired: true,
      })
      .expect(201);

    expect(response.body.status).toBe('PENDIENTE');
    expect(response.body.clientId).toBe(clientId);
  });

  it('6. POST /inspections rechaza un segundo registro para el mismo cliente', async () => {
    await request(app.getHttpServer())
      .post('/inspections')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        clientId,
        inspectorName: 'Otro inspector',
        systemType: 'MONOFASICO',
        originPoint: 'Caja de medidores',
        hasPanelSpace: false,
        requiresDrilling: true,
        differentialProtectionRequired: false,
      })
      .expect(409);
  });
});