import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { cleanDatabase } from '../src/utils/database.util';

describe('Ruta Crítica CRM: Eventos y Embudo (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let accessToken: string;

  // Variables para seguir el rastro del flujo
  let campaignId: string;
  let leadId: string;
  let dealId: string;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true }));
    await app.init();

    prisma = app.get(PrismaService);
    await cleanDatabase(prisma);

    // Setup de autenticación
    const testEmail = `admin-${Date.now()}@econexium.com`;
    await request(app.getHttpServer())
      .post('/users')
      .send({ name: 'Admin Flow', email: testEmail, password: 'Password123!', role: 'admin' });

    const loginRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({ email: testEmail, password: 'Password123!' });

    accessToken = loginRes.body.accessToken;
  });

  afterAll(async () => {
    await cleanDatabase(prisma);
    await app.close();
  });

  it('1. POST /campaigns restringe la creación a canales permitidos', async () => {
    // Probamos primero que falle si le pasamos un canal inválido
    await request(app.getHttpServer())
      .post('/campaigns')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({ name: 'Campaña Fallida', channel: 'tiktok' })
      .expect(400);

    // Creamos la campaña válida
    const response = await request(app.getHttpServer())
      .post('/campaigns')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        name: 'Promo Cargadores EV',
        channel: 'facebook', // Canal permitido en tu array ALLOWED_CHANNELS
      })
      .expect(201);

    campaignId = response.body.id;
  });

  it('2. POST /leads enlaza correctamente con la campaña', async () => {
    const response = await request(app.getHttpServer())
      .post('/leads')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        campaignId,
        name: 'Carlos FB',
        email: 'carlos@test.com',
        phone: '3001234567'
        // Agrega aquí cualquier otro campo obligatorio de tu CreateLeadDto
      })
      .expect(201);

    leadId = response.body.id;
  });

  it('3. POST /deals crea el trato sin permitir duplicados', async () => {
    const res = await request(app.getHttpServer())
      .post('/deals')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        leadId,
        installationType: 'CARGADOR', // Debe ser SOLAR, CARGADOR o AMBOS según tu DTO
        estimatedValue: 2500000
      });

    if (res.status !== 201) {
      console.log('🚨 ERROR DE VALIDACIÓN EN DEALS:', res.body);
    }

    expect(res.status).toBe(201);
    dealId = res.body.id;

    // Intento de duplicado para probar la ConflictException
    // estimatedValue es requerido en el DTO (no tiene @IsOptional),
    // así que debe enviarse también aquí para que la petición pase
    // el ValidationPipe y llegue a la lógica de negocio del service.
    await request(app.getHttpServer())
      .post('/deals')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({
        leadId,
        installationType: 'CARGADOR',
        estimatedValue: 2500000
      })
      .expect(409);
  });

  it('4. PATCH /deals/:id a GANADO emite evento y crea el Cliente automáticamente', async () => {
    // Actualizamos el trato a GANADO (esto dispara this.eventEmitter.emit)
    await request(app.getHttpServer())
      .patch(`/deals/${dealId}`)
      .set('Authorization', `Bearer ${accessToken}`)
      .send({ stage: 'GANADO' })
      .expect(200);

    // TRUCO: Los eventos son asíncronos. Le damos 100ms a Nest para que
    // termine de ejecutar el 'handleDealWon' en ClientsService antes de consultar.
    await new Promise(resolve => setTimeout(resolve, 100));

    // Verificamos que el cliente se haya creado en la base de datos
    const clientsResponse = await request(app.getHttpServer())
      .get('/clients')
      .set('Authorization', `Bearer ${accessToken}`)
      .expect(200);

    // Buscamos al cliente generado a partir de este trato
    const autoGeneratedClient = clientsResponse.body.find(c => c.dealId === dealId);

    expect(autoGeneratedClient).toBeDefined();
    expect(autoGeneratedClient.name).toBe('Carlos FB'); // Heredó los datos del Lead
    expect(autoGeneratedClient.email).toBe('carlos@test.com');
  });
});